--GRUPO A
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Algicultura', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Algicultura', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Carcinicultura em Viveiros Escavados em Apicuns e Salgados', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Carcinicultura em Viveiros Escavados em Apicuns e Salgados', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Carcinicultura em Viveiros Escavados', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Carcinicultura em Viveiros Escavados', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Madeira de floresta nativa advinda de supressão ou manejo', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Madeira de floresta nativa advinda de supressão ou manejo', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Madeira de floresta plantada', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Madeira de floresta plantada', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Malacocultura', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Malacocultura', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Piscicultura Continental em Tanques-Rede, Raceway ou Similar', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Piscicultura Continental em Tanques-Rede, Raceway ou Similar', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Piscicultura marinha em tanques-rede, raceway ou similar', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Piscicultura marinha em tanques-rede, raceway ou similar', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Ranicultura', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Ranicultura', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Silvicultura vinculada a PSS', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Silvicultura vinculada a PSS', null, 2, null, null, 3600);
--GRUPO A ESPECIAIS
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Aves e pequenos mamíferos', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Aves e pequenos mamíferos', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Bovinos, bubalinos, muares e equinos', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Bovinos, bubalinos, muares e equinos', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Caprinos e ovinos', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Caprinos e ovinos', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Creche de suínos', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Creche de suínos', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Piscicultura em Viveiros Escavados ou similar', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Piscicultura em Viveiros Escavados ou similar', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Suínos', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Suínos', null, 2, null, null, 3600);

--GRUPO B
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Ágata, Água Marinha, Alexandrita, Berilo, Calcedônia, Cianita, Citrino, Crisoberilo, Granada, Heliotrópio, Jacinto, Jade, Jaspe, Lapis-Lazuli, Lazurita, Olho de Tigre, Opala, Rubi, Safira, Topázio, Turmalina, Turquesa e outras', null, 1, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Ágata, Água Marinha, Alexandrita, Berilo, Calcedônia, Cianita, Citrino, Crisoberilo, Granada, Heliotrópio, Jacinto, Jade, Jaspe, Lapis-Lazuli, Lazurita, Olho de Tigre, Opala, Rubi, Safira, Topázio, Turmalina, Turquesa e outras', null, 2, null, null, 6000);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Alumínio, Antimônio, Cádmio, Chumbo, Cobre, Cromo, Escândio, Estanho, Estrôncio, Frâncio, Gálio, Germânio, Háfnio, Índio, Irídio, Ítrio, Lítio, Molibdênio, Niobio, Níquel, Osmio, Ouro, Paládio, Platina, Prata, Rodio, Rubídio, Selênio, Tálio, Tântalo, Tecnécio, Titânio, Tungstênio, Vanádio, Zinco e Zircônio', null, 1, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Alumínio, Antimônio, Cádmio, Chumbo, Cobre, Cromo, Escândio, Estanho, Estrôncio, Frâncio, Gálio, Germânio, Háfnio, Índio, Irídio, Ítrio, Lítio, Molibdênio, Niobio, Níquel, Osmio, Ouro, Paládio, Platina, Prata, Rodio, Rubídio, Selênio, Tálio, Tântalo, Tecnécio, Titânio, Tungstênio, Vanádio, Zinco e Zircônio', null, 2, null, null, 6000);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Ametista, Diamante e Esmeralda', null, 1, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Ametista, Diamante e Esmeralda', null, 2, null, null, 6000);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Amianto', null, 1, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Amianto', null, 2, null, null, 6000);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Andalusita, Anfibólios, Caulinita, Coríndon, Feldspato, Grafita, Moscovita, Pegmatito, Quartzito Serpentinito, Silex,Vermiculita, Wollastonita, Xisto e Zirconita, Dentre Outros, Para Uso Industrial Não Especificado Anteriormente', null, 1, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Andalusita, Anfibólios, Caulinita, Coríndon, Feldspato, Grafita, Moscovita, Pegmatito, Quartzito Serpentinito, Silex,Vermiculita, Wollastonita, Xisto e Zirconita, Dentre Outros, Para Uso Industrial Não Especificado Anteriormente', null, 2, null, null, 6000);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Anidrita, Barita, Bentonita, Calcário Conchífero, Calcário Calcítico, Calcita, Diatomita, Gipsita, Magnesita e Talco', null, 1, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Anidrita, Barita, Bentonita, Calcário Conchífero, Calcário Calcítico, Calcita, Diatomita, Gipsita, Magnesita e Talco', null, 2, null, null, 6000);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Apatita, Calcário Dolomítico, Calcita, Carnalita, Dolomita, Fosfatos, Minerais de Borato, Potássio, Salgema, Salitre, Silvita e Sódio, Dentre Outros, Para Produção de Fertilizantes e Corretivos Agrícolas, etc', null, 1, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Apatita, Calcário Dolomítico, Calcita, Carnalita, Dolomita, Fosfatos, Minerais de Borato, Potássio, Salgema, Salitre, Silvita e Sódio, Dentre Outros, Para Produção de Fertilizantes e Corretivos Agrícolas, etc', null, 2, null, null, 6000);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Ardósia, Dioritos, Granitos, Mármores, Quartzos, Sienitos, dentre outras utilizadas para revestimento', null, 1, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Ardósia, Dioritos, Granitos, Mármores, Quartzos, Sienitos, dentre outras utilizadas para revestimento', null, 2, null, null, 6000);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Areias, Arenoso, Cascalhos, Filitos e Saibro', null, 1, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Areias, Arenoso, Cascalhos, Filitos e Saibro', null, 2, null, null, 6000);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Areias em Recursos Hídricos', null, 1, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Areias em Recursos Hídricos', null, 2, null, null, 6000);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Argilas, Caulinita,Diatomita, Ilita, Caulim, dentre outros)', null, 1, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Argilas, Caulinita,Diatomita, Ilita, Caulim, dentre outros)', null, 2, null, null, 6000);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Basalto, Calcários, Gnaisses, Granitos, Granulitos,  Metarenitos, Quartzitos, Sienitos, dentre outras utilizadas para a produção de agregados e beneficiamento associado (britamento)', null, 1, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Basalto, Calcários, Gnaisses, Granitos, Granulitos,  Metarenitos, Quartzitos, Sienitos, dentre outras utilizadas para a produção de agregados e beneficiamento associado (britamento)', null, 2, null, null, 6000);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Caulim', null, 1, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Caulim', null, 2, null, null, 6000);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Cianita, Feldspato, Leucita, Moscovita, Nefelina, Quartzo e Turmalina, Dentre Outros, Para Manufatura de Vidro/Vitrificação, Esmaltação e Indústria óptica, Eletrônica, etc.', null, 1, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Cianita, Feldspato, Leucita, Moscovita, Nefelina, Quartzo e Turmalina, Dentre Outros, Para Manufatura de Vidro/Vitrificação, Esmaltação e Indústria óptica, Eletrônica, etc.', null, 2, null, null, 6000);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Combustíveis Fósseis Sólidos (carvão, linhito, turfa e sapropelitos, dentre outros)', null, 1, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Combustíveis Fósseis Sólidos (carvão, linhito, turfa e sapropelitos, dentre outros)', null, 2, null, null, 6000);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Criolita, Enxofre, Fluorita, Selênio, Silício, Silicatos e Telúrio', null, 1, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Criolita, Enxofre, Fluorita, Selênio, Silício, Silicatos e Telúrio', null, 2, null, null, 6000);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Ferro', null, 1, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Ferro', null, 2, null, null, 6000);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Manganês', null, 1, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Manganês', null, 2, null, null, 6000);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Perfuração de Poços de Petróleo ou Gás Natural', null, 1, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Perfuração de Poços de Petróleo ou Gás Natural', null, 2, null, null, 6000);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Petróleo cru e gás natural', null, 1, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Petróleo cru e gás natural', null, 2, null, null, 6000);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Rochas betuminosas e pirobetuminosas (xisto betuminoso e xisto pirobetuminoso)', null, 1, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Rochas betuminosas e pirobetuminosas (xisto betuminoso e xisto pirobetuminoso)', null, 2, null, null, 6000);

--GRUPO C
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Abate de aves', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Abate de aves', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Ácidos Inorgânicos', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Ácidos Inorgânicos', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Ácidos Orgânicos', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Ácidos Orgânicos', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Água Mineral', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Água Mineral', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Alcoóis', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Alcoóis', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Aminas', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Aminas', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Anilinas', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Anilinas', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Aparelhamento de mármore, ardósia, granito e outras', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Aparelhamento de mármore, ardósia, granito e outras', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Áreas Industriais', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Áreas Industriais', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Beneficiamento de borracha natural', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Beneficiamento de borracha natural', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Beneficiamento de carnes', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Beneficiamento de carnes', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Beneficiamento de couros e peles com uso de produto químico', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Beneficiamento de couros e peles com uso de produto químico', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Beneficiamento de couros e peles sem uso de produto químico (salgadeira)', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Beneficiamento de couros e peles sem uso de produto químico (salgadeira)', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Beneficiamento, fiação ou tecelagem de fibras têxteis', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Beneficiamento, fiação ou tecelagem de fibras têxteis', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Biocombustível', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Biocombustível', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Borrachas sintéticas', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Borrachas sintéticas', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Cianetos Inorgânicos', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Cianetos Inorgânicos', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Cloretos inorgânicos', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Cloretos inorgânicos', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Cloretos orgânicos', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Cloretos orgânicos', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Cloro e Álcalis', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Cloro e Álcalis', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Corantes e Pigmentos Orgânicos', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Corantes e Pigmentos Orgânicos', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Desdobramento (pranchas, dormentes e pranchões), fabricação de madeira compensada, folheada e laminada', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Desdobramento (pranchas, dormentes e pranchões), fabricação de madeira compensada, folheada e laminada', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Destiladas (aguardente, whisky e outros)', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Destiladas (aguardente, whisky e outros)', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Equipamentos Elétricos Industriais, Aparelhos Eletrodomésticos, Fabricação de Materiais Elétricos, Computadores, Acessórios e Equipamentos De Escritório, Fabricação de Componentes e Acessórios Eletrônicos ou Equipamentos de Informática', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Equipamentos Elétricos Industriais, Aparelhos Eletrodomésticos, Fabricação de Materiais Elétricos, Computadores, Acessórios e Equipamentos De Escritório, Fabricação de Componentes e Acessórios Eletrônicos ou Equipamentos de Informática', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Equipamentos para transmissão e distribuição de energia elétrica', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Equipamentos para transmissão e distribuição de energia elétrica', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Ésteres', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Ésteres', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Éteres', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Éteres', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de absorventes e fraldas descartáveis', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de absorventes e fraldas descartáveis', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de artefatos de barro e cerâmica', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de artefatos de barro e cerâmica', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de artefatos de borracha ou plástico (baldes, PET, elástico e assemelhados)', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de artefatos de borracha ou plástico (baldes, PET, elástico e assemelhados)', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de artefatos de cimento, pó de mármore e concreto', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de artefatos de cimento, pó de mármore e concreto', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de artefatos de fibroamianto e fibra de vidro', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de artefatos de fibroamianto e fibra de vidro', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de Artefatos de Madeira com Tratamento (Pintura, Verniz, Cola e Assemelhados)', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de Artefatos de Madeira com Tratamento (Pintura, Verniz, Cola e Assemelhados)', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de artigos de couro ', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de artigos de couro ', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de artigos têxteis com lavagem e/ou pintura', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de artigos têxteis com lavagem e/ou pintura', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de Bicicletas', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de Bicicletas', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de calçados, bolsas, acessórios e semelhantes ', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de calçados, bolsas, acessórios e semelhantes ', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de Cal e Assemelhados', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de Cal e Assemelhados', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de carrocerias', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de carrocerias', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de celulose', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de celulose', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de centrais telefônicas, equipamentos e acessórios de radio telefonia e fabricação e montagem de televisores rádios e sistemas de som', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de centrais telefônicas, equipamentos e acessórios de radio telefonia e fabricação e montagem de televisores rádios e sistemas de som', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de Cimento', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de Cimento', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de equipamentos e acessórios para segurança e proteção pessoal e profissional', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de equipamentos e acessórios para segurança e proteção pessoal e profissional', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de farinhas, amidos,féculas de cereais, macarrão, biscoitos e assemelhados ', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de farinhas, amidos,féculas de cereais, macarrão, biscoitos e assemelhados ', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de Gesso, Produtos e Artefatos', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de Gesso, Produtos e Artefatos', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de locomotivas e vagões', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de locomotivas e vagões', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de mídias virgens, magnéticas e ópticas', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de mídias virgens, magnéticas e ópticas', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de óleos, margarina e outras gorduras vegetais', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de óleos, margarina e outras gorduras vegetais', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de papel', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de papel', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de pneus e câmaras de ar', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de pneus e câmaras de ar', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de produtos de papel ondulado, cartolina, papelão, papel cartão ou semelhantes, papel higiênico, produtos para uso doméstico, bem como embalagens.', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de produtos de papel ondulado, cartolina, papelão, papel cartão ou semelhantes, papel higiênico, produtos para uso doméstico, bem como embalagens.', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de ração animal', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de ração animal', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de refratários, pisos e azulejos ou semelhantes', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de refratários, pisos e azulejos ou semelhantes', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de soldas e anodos', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de soldas e anodos', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de telas e outros artigos de arame, ferragens, ferramentas de corte, fios metálicos e trefilados, pregos, tachas, latas e tampas e semelhantes', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de telas e outros artigos de arame, ferragens, ferramentas de corte, fios metálicos e trefilados, pregos, tachas, latas e tampas e semelhantes', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de tubos de ferro e aço, tonéis, estruturas metálicas e semelhantes', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação de tubos de ferro e aço, tonéis, estruturas metálicas e semelhantes', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação do vidro ', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação do vidro ', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação e beneficiamento de espuma (poliuretano e assemelhados)', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação e beneficiamento de espuma (poliuretano e assemelhados)', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação e Mistura de Perfumes, Cosméticos e Preparados Para Higiene Pessoal', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação e Mistura de Perfumes, Cosméticos e Preparados Para Higiene Pessoal', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação e Mistura de Produtos de Limpeza, Polimento e Para Uso Sanitário.', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação e Mistura de Produtos de Limpeza, Polimento e Para Uso Sanitário.', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação e montagem de aeronaves', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação e montagem de aeronaves', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação e montagem de embarcações e plataformas', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação e montagem de embarcações e plataformas', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação e montagem de veículos automotores, trailers e semelhantes', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação e montagem de veículos automotores, trailers e semelhantes', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação e/ou montagem de motocicletas e triciclos', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fabricação e/ou montagem de motocicletas e triciclos', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fermentadas (vinhos, cervejas e outros)', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fermentadas (vinhos, cervejas e outros)', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fertilizantes e Defensivos Agrícolas', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fertilizantes e Defensivos Agrícolas', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fibras Sintéticas', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fibras Sintéticas', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fluoretos', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Fluoretos', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Frigorífico e/ou abate de bovinos, eqüinos, muares.', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Frigorífico e/ou abate de bovinos, eqüinos, muares.', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Frigorífico e/ou abate de caprinos, suínos.', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Frigorífico e/ou abate de caprinos, suínos.', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Gases Industriais', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Gases Industriais', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Glicóis', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Glicóis', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Hidróxidos', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Hidróxidos', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Industrialização da Mandioca', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Industrialização da Mandioca', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Industrialização de frutas, verduras e legumes (compotas, geléias, polpas, doces, etc.)', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Industrialização de frutas, verduras e legumes (compotas, geléias, polpas, doces, etc.)', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Metalurgia de metais preciosos', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Metalurgia de metais preciosos', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Metalurgia e fundição de metais ferrosos', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Metalurgia e fundição de metais ferrosos', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Metalurgia e fundição de metais não ferrosos', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Metalurgia e fundição de metais não ferrosos', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Mistura para Fertilizantes', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Mistura para Fertilizantes', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Motores e Turbinas, Máquinas, Peças, Acessórios e equipamentos', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Motores e Turbinas, Máquinas, Peças, Acessórios e equipamentos', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Não alcoólicas (refrigerantes, chá, sucos e assemelhados)', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Não alcoólicas (refrigerantes, chá, sucos e assemelhados)', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Óleos e graxas lubrificantes', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Óleos e graxas lubrificantes', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Óxidos, Dióxidos e Peróxidos', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Óxidos, Dióxidos e Peróxidos', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Pasteurização e derivados do leite', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Pasteurização e derivados do leite', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Pigmentos Inorgânicos', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Pigmentos Inorgânicos', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Plastificantes', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Plastificantes', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Processamento e fabricação de cigarros, cigarrilhas, charutos e assemelhados', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Processamento e fabricação de cigarros, cigarrilhas, charutos e assemelhados', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Produção de argamassa', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Produção de argamassa', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Produção e refino de açúcar industrial', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Produção e refino de açúcar industrial', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Produtos Farmacêuticos', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Produtos Farmacêuticos', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Produtos Petroquímicos Básicos e intermediários', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Produtos Petroquímicos Básicos e intermediários', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Recondicionamento de pneus', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Recondicionamento de pneus', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Refino e Re-refino do Petróleo', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Refino e Re-refino do Petróleo', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Resinas Termofixas', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Resinas Termofixas', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Resinas Termoplásticas', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Resinas Termoplásticas', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Siderurgia', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Siderurgia', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Solventes industriais', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Solventes industriais', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Substâncias orgânicas cloradas e/ou nitradas', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Substâncias orgânicas cloradas e/ou nitradas', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Sulfatos', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Sulfatos', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Tintas, vernizes, esmaltes, lacas, solventes e produtos correlatos', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Tintas, vernizes, esmaltes, lacas, solventes e produtos correlatos', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Usina de Asfalto e Emulsão Asfáltica', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Usina de Asfalto e Emulsão Asfáltica', null, 2, null, null, 3600);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Velas', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Velas', null, 2, null, null, 3600);

--GRUPO D
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Bases operacionais de transportadora de produtos e/ou resíduos perigosos, com lavagem interna e/ou externa', null, 1, null, null, 1500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Bases operacionais de transportadora de produtos e/ou resíduos perigosos, com lavagem interna e/ou externa', null, 2, null, null, 2400);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Bases operacionais de transporte ferroviários, aéreo de cargas, transportadora de passageiros e cargas não perigosas', null, 1, null, null, 1500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Bases operacionais de transporte ferroviários, aéreo de cargas, transportadora de passageiros e cargas não perigosas', null, 2, null, null, 2400);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Dutos de Petróleo Cru (Oleodutos), de petróleo refinado, gasolina, derivados de petróleo, gases, produtos químicos diversos e minérios', null, 1, null, null, 1500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Dutos de Petróleo Cru (Oleodutos), de petróleo refinado, gasolina, derivados de petróleo, gases, produtos químicos diversos e minérios', null, 2, null, null, 2400);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Transportadora de resíduos e/ou produtos perigosos e de serviços de saúde', null, 1, null, null, 1500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Transportadora de resíduos e/ou produtos perigosos e de serviços de saúde', null, 2, null, null, 2400);

--GRUPO E
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Áreas de Bota-Fora', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Áreas de Bota-Fora', null, 2, null, null, 3500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Aterro e estocagem de resíduos industriais', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Aterro e estocagem de resíduos industriais', null, 2, null, null, 3500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Aterros Sanitários', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Aterros Sanitários', null, 2, null, null, 3500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Blending', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Blending', null, 2, null, null, 3500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Cemitérios', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Cemitérios', null, 2, null, null, 3500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Concreto e argamassa', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Concreto e argamassa', null, 2, null, null, 3500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Construção de Linhas de Distribuição de Energia Elétrica > 69 Kv', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Construção de Linhas de Distribuição de Energia Elétrica > 69 Kv', null, 2, null, null, 3500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Construção de linhas de transmissão de energia elétrica ', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Construção de linhas de transmissão de energia elétrica ', null, 2, null, null, 3500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Construção ou ampliação de sistema de abastecimento público de água (captação, adução, tratamento, reservação)', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Construção ou ampliação de sistema de abastecimento público de água (captação, adução, tratamento, reservação)', null, 2, null, null, 3500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Construção ou ampliação de sistema de esgotamento sanitário (redes de coleta, interceptores, tratamento e disposição final de esgotos domésticos)', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Construção ou ampliação de sistema de esgotamento sanitário (redes de coleta, interceptores, tratamento e disposição final de esgotos domésticos)', null, 2, null, null, 3500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Entrepostos Aduaneiros de Produtos Não Perigosos, Terminais de Estocagem e Distribuição de Produtos Não Perigosos e Não Classificados', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Entrepostos Aduaneiros de Produtos Não Perigosos, Terminais de Estocagem e Distribuição de Produtos Não Perigosos e Não Classificados', null, 2, null, null, 3500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Estação de Compressão e distribuição de gás natural', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Estação de Compressão e distribuição de gás natural', null, 2, null, null, 3500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Estação de Custódia (Ponto de Entrega)', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Estação de Custódia (Ponto de Entrega)', null, 2, null, null, 3500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Estações de tratamento e equipamentos associados', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Estações de tratamento e equipamentos associados', null, 2, null, null, 3500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Estações rádio-base de telefonia celular', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Estações rádio-base de telefonia celular', null, 2, null, null, 3500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Estocagem de gás natural', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Estocagem de gás natural', null, 2, null, null, 3500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Estocagem de GLP', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Estocagem de GLP', null, 2, null, null, 3500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Geração de Energia Elétrica por Fonte Eólica', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Geração de Energia Elétrica por Fonte Eólica', null, 2, null, null, 3500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Geração de Energia Solar Fotovoltaica', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Geração de Energia Solar Fotovoltaica', null, 2, null, null, 3500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Hidrelétricas ', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Hidrelétricas ', null, 2, null, null, 3500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Landfarming', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Landfarming', null, 2, null, null, 3500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Manutenção industrial, jateamento, pintura e correlatos', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Manutenção industrial, jateamento, pintura e correlatos', null, 2, null, null, 3500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Postos de Venda de Gasolina e Outros Combustíveis', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Postos de Venda de Gasolina e Outros Combustíveis', null, 2, null, null, 3500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Reciclagem de Materiais Metálicos, Triagem de Materiais Recicláveis (Que Inclua Pelo Menos Uma Etapa do Processo de Industrialização)', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Reciclagem de Materiais Metálicos, Triagem de Materiais Recicláveis (Que Inclua Pelo Menos Uma Etapa do Processo de Industrialização)', null, 2, null, null, 3500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Reciclagem de Papel, Papelão e Similares, Vidros e de Materiais Plásticos', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Reciclagem de Papel, Papelão e Similares, Vidros e de Materiais Plásticos', null, 2, null, null, 3500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Serviços de Britagem, Resíduos da Construção Civil e outros', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Serviços de Britagem, Resíduos da Construção Civil e outros', null, 2, null, null, 3500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Serviços de calderaria, usinagem, solda, tratamento e revestimento em metais', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Serviços de calderaria, usinagem, solda, tratamento e revestimento em metais', null, 2, null, null, 3500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Serviços de descontaminação de lâmpadas fluorescentes ou reciclagem', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Serviços de descontaminação de lâmpadas fluorescentes ou reciclagem', null, 2, null, null, 3500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Serviços de Lavagem, Descontaminação e Manutenção de Tanques e Isotanques', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Serviços de Lavagem, Descontaminação e Manutenção de Tanques e Isotanques', null, 2, null, null, 3500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Sistemas e Disposição Oceânica', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Sistemas e Disposição Oceânica', null, 2, null, null, 3500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Terminais de minério', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Terminais de minério', null, 2, null, null, 3500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Terminais de petróleo e derivados e de produtos químicos diversos', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Terminais de petróleo e derivados e de produtos químicos diversos', null, 2, null, null, 3500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Terminais de produtos agrícolas industrializados', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Terminais de produtos agrícolas industrializados', null, 2, null, null, 3500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Terminais de Regaseificação GNL', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Terminais de Regaseificação GNL', null, 2, null, null, 3500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Termoelétricas ou Grupos Geradores', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Termoelétricas ou Grupos Geradores', null, 2, null, null, 3500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Tinturaria e Lavanderias Industrial/Hospitalar', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Tinturaria e Lavanderias Industrial/Hospitalar', null, 2, null, null, 3500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Usinas de compostagem e triagem de materiais e resíduos urbanos', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Usinas de compostagem e triagem de materiais e resíduos urbanos', null, 2, null, null, 3500);
--GRUPO E ESPECIAIS
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Incineradores  de Resíduos Industriais e de Saúde', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Incineradores  de Resíduos Industriais e de Saúde', null, 2, null, null, 3500);

--GRUPO F
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', ' Aeroportos ', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', ' Aeroportos ', null, 2, null, null, 3500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Autódromos e aeródromos', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Autódromos e aeródromos', null, 2, null, null, 3500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Barragens e Diques', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Barragens e Diques', null, 2, null, null, 3500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Canais', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Canais', null, 2, null, null, 3500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Complexos Viários (Implantação ou Ampliação de estradas, pontes e afins)', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Complexos Viários (Implantação ou Ampliação de estradas, pontes e afins)', null, 2, null, null, 3500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', ' Ferrovias', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', ' Ferrovias', null, 2, null, null, 3500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Hidrovias', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Hidrovias', null, 2, null, null, 3500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', ' Marinas e atracadouros e instalações de manutenção de embarcações', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', ' Marinas e atracadouros e instalações de manutenção de embarcações', null, 2, null, null, 3500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Metrôs', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Metrôs', null, 2, null, null, 3500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Portos', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Portos', null, 2, null, null, 3500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Retificação de cursos d´água', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Retificação de cursos d´água', null, 2, null, null, 3500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Transposição de bacias hidrográficas', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Transposição de bacias hidrográficas', null, 2, null, null, 3500);

--GRUPO G
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Complexos Turísticos e Empreendimentos Hoteleiros', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Complexos Turísticos e Empreendimentos Hoteleiros', null, 2, null, null, 3500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Conjuntos Habitacionais', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Conjuntos Habitacionais', null, 2, null, null, 3500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Estádios de Futebol, Parques Temáticos, de Diversão e de Exposição, Jardins Botânicos', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Estádios de Futebol, Parques Temáticos, de Diversão e de Exposição, Jardins Botânicos', null, 2, null, null, 3500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Habitação de Interesse Social', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Habitação de Interesse Social', null, 2, null, null, 3500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Parcelamento do Solo (Loteamentos, Desmembramentos)', null, 1, null, null, 2500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Parcelamento do Solo (Loteamentos, Desmembramentos)', null, 2, null, null, 3500);

--GRUPO H
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Abatedouros e frigoríficos', null, 1, null, null, 1500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Abatedouros e frigoríficos', null, 2, null, null, 2400);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Criadouros comerciais', null, 1, null, null, 1500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Criadouros comerciais', null, 2, null, null, 2400);
--GRUPO H ESPECIAIS
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Criadouros científicos, CRAS, CETAS e mantenedores', null, 1, null, null, 1500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Criadouros científicos, CRAS, CETAS e mantenedores', null, 2, null, null, 2400);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Criadouros comerciais de abelhas', null, 1, null, null, 1500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Criadouros comerciais de abelhas', null, 2, null, null, 2400);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Zoológicos', null, 1, null, null, 1500);
select atualizar_taxas_parametro_calculo ('Licença Unificada (LU)', 'Zoológicos', null, 2, null, null, 2400);
