alter table FCE_ENERGIA_TERMOELETRICA_UNIDADE add column qtd_agua_energia_termoeletrica_unidade numeric(10,2);
alter table FCE_ENERGIA_TERMOELETRICA_UNIDADE add column vapor_gerado_energia_termoeletrica_unidade numeric(10,2);
