package br.gov.ba.seia.enumerator;

import java.io.File;

public enum DiretorioArquivoEnum {

	PESSOA("PESSOA"),
	REPRESENTANTE_LEGAL("REPRESENTANTE_LEGAL"),
	PROCURADOR_REPRESENTANTE("PROCURADOR_REPRESENTANTE"),
	PROCURADOR_PESSOA_FISICA("PROCURADOR_PESSOA_FISICA"),
	EMPREENDIMENTO("EMPREENDIMENTO"),
	PROCESSO("PROCESSO"),
	DOCUMENTOOBRIGATORIO("DOCUMENTOOBRIGATORIO"),
	DOCUMENTOIDENTIFICACAO("DOCUMENTOIDENTIFICACAO"),
	DOCUMENTO_IDENTIFICACAO_REQUERIMENTO("DOCUMENTO_IDENTIFICACAO_REQUERIMENTO"),
	DOCUMENTO_REPRESENTACAO_REQUERIMENTO("DOCUMENTO_REPRESENTACAO_REQUERIMENTO"),
	BOLETO_REQUERIMENTO("boleto"),
	IMOVELRURAL("IMOVELRURAL"),
	SHAPEFILES("SHAPES"),
	SHAPEFILESTEMP("SHAPESTEMP"),
	IMPORTACAOCDACEFIR("IMPORTACAOCDACEFIR"),
	CAEPOG("CAEPOG"),
	CADASTROS_AMBIENTAIS("CADASTRO_AMBIENTAL"),
	PESQUISA_MINERAL(DiretorioArquivoEnum.CADASTROS_AMBIENTAIS.toString(), "PESQUISA_MINERAL"),
	ATOS_DECLARATORIOS("ATOS_DECLARATORIOS"),
	DIAP(DiretorioArquivoEnum.ATOS_DECLARATORIOS.toString(), "DIAP"), 
	TCCA("TCCA"),
	CERH("CERH"),
	REENQUADRAMENTO("REENQUADRAMENTO"),
	DOCUMENTO_REQUERIMENTO_EMPREENDIMENTO("DOCUMENTO_REQUERIMENTO_EMPREENDIMENTO"),
	SEFAZ("SEFAZ"),
	PCT("PCT"),
	SILOS_ARMAZENS(DiretorioArquivoEnum.CADASTROS_AMBIENTAIS.toString(), "SILOS_ARMAZENS");
	
	private String caminho;

	private DiretorioArquivoEnum(String caminho) {
		this.caminho = File.separator + "opt" + File.separator + "ARQUIVOS" + File.separator + caminho + File.separator;
	}

	private DiretorioArquivoEnum(String diretorio, String caminho) {
		this.caminho = diretorio.toString() + caminho;
	}

	@Override
	public String toString() {
		return this.caminho;
	}
}
