package br.gov.ba.seia.enumerator;

import br.gov.ba.seia.entity.DocumentoObrigatorio;

public enum DocumentoObrigatorioEnum {

	ERB(104),
	POSTO(105),
	COMPROVANTE_ATUALIZADO_RAF(124),
	TRANSPORTADORA(1263),
	AGROSSILVOPASTORIL(139),
	FCE_ASV(2000),
	FCE_CONSTRUCAO_BARRAGEM(10074),
	FCE_INTERVENCAO_BARRAGEM(1437),
	FCE_INTERVENCAO_BARRAGEM_SEM_PONTO(97),
	ESTUDO_HIDROLOGICO(9999),
	FCE_OUTORGA_CAPTACAO_SUPERFICIAL(1436),
	FCE_CAPTACAO_SUPERFICIAL_ADICIONAIS(9998),
	FCE_OUTORGA_INTERVENCAO_ABASTECIMENTO_HUMANO(1419),
	FCE_OUTORGA_CAPTACAO_SUBTERRANEA(1435),
	FCE_OUTORGA_CAPTACAO_SUBTERRANEA_DADOS_ADICIONAIS(9991),
	FCE_PULVERIZACAO(1434),
	FCE_PULVERIZACAO_ADICIONAIS(9987),
	FCE_ABASTECIMENTO_INDUSTRIAL(1432),
	FCE_ABASTECIMENTO_INDUSTRIAL_ADICIONAIS(9988),
	FCE_LOCALIZACAO_GEOGRAFICA(1439),
	FCE_LOCALIZACAO_GEOGRAFICA_DADOS_ADICIONAIS(9981),
	FCE_IRRIGACAO(1433),
	FCE_DESSEDENTACAO_ANIMAL(9982),
	FCE_LANCAMENTO_EFLUENTES(1440),
	FCE_LANCAMENTO_EFLUENTES_ADICIONAIS(9978),
	FCE_INDUSTRIA(1458),
	FCE_OUTORGA_AQUICULTURA(1444),
	FCE_OUTORGA_AQUICULTURA_ADICIONAIS(9990),
	FCE_TURISMO(9989),
	FCE_TURISMO_ADICIONAIS(9986),
	FCE_LICENCIAMENTO_AQUICULTURA(9997),
	FCE_LICENCIAMENTO_AQUICULTURA_ADICIONAIS(9996),
	FCE_CANAIS(10070),
	COMPROVACAO_DA_CONCESSAO_DE_AUTORIZACAO_DE_SUPRESSAO_DE_VEGETACAO_NATIVA_22_DE_JULHO_DE_2008(10027),
	COMPROVACAO_DA_CONCESSAO_DE_OUTORGA_DE_DIREITO_DE_USO_DE_RECURSOS_HIDRICOS_OU_DECLARACAO_DE_DISPENSA(10028),
	CERTIDAO_MUNICIPAL_DE_REGULAR_USO_E_OCUPACAO_DO_SOLO(10029),
	ANUENCIA_DO_ORGAO_GESTOR_DA_UC(10030),
	TERMO_DE_COMPROMISSO_CERTIFICADO_DO_CEFIR_OU_RECIBO_DO_CAR(10031),
	DECLARACAO_DA_ATIVIDADE_ANTROPICA(10032),
	FORMULARIO_DE_CARACTERIZACAO_DO_EMPREENDIMENTO_AGROSSILVIPASTORIL(10033),
	FCE_AUTORIZACAO_MINERACAO(3001),
	FCE_LICENCIAMENTO_MINERACAO(3000),
	FORMULARIO_DIAP(10048),
	FORMULARIO_RFP(10049),
	FORMULARIO_DQC(10050),
	DTRP_DOCUMENTO_1(1324),
	DTRP_DOCUMENTO_2(1325),
	DTRP_DOCUMENTO_3(1326),
	DTRP_DOCUMENTO_4(1328),
	DTRP_DOCUMENTO_5(10043),
	DTRP_DOCUMENTO_6(10044),
	DTRP_DOCUMENTO_7(10045),
	PROCURACAO(10062),
	FCE_INFRAESTRUTURA(10072),
	FCE_SISTEMA_ABASTECIMENTO_AGUA(10075),
	FCE_CARACTERIZACAO_SES(10076),
	FCE_GERACAO_ENERGIA(10077),
	FCE_LINHA_DE_TRASMISSAO_DISTRIBUICAO_ENERGIA(10078),
	FCE_INTERVENCAO_MINERACAO(3002),
	FCE_EPMF(10081),
	CRF_DISPONIBILIZACAO_AUTO_INFRACAO(10084),
	CRF_DISPONIBILIZACAO_PORTARIA_ATO_AUTORIZATIVO_FLORESTAL(10085),
	TERMO_COMPROMISSO_APE(10087),
	COPIA_PORTARIA_OUTORGA_CAPTACAO_A_SER_REALIZADA(10089),
	COPIA_PORTARIA_OUTORGA_LANCAMENTO_EFLUENTES_A_SER_REALIZADA(10090),
	CERTIFICADO_MADEIRA_NATIVA(10092),
	CERTIFICADO_MADEIRA_EXOTICA(10093),
	AUTORIZACAO_PROPRIETARIO_SUPERFICIARIO(10039),
	CRF_DISPONIBILIZACAO_PORTARIA_ATO_AUTORIZATIVO_FLORESTAL_ASV_AML(10086)
	;

	private Integer id;

	DocumentoObrigatorioEnum(Integer id){
		this.id = id;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public static DocumentoObrigatorioEnum getEnum(DocumentoObrigatorio documentoObrigatorio){
		DocumentoObrigatorioEnum[] enums = DocumentoObrigatorioEnum.values();
		for (DocumentoObrigatorioEnum documentoObrigatorioEnum : enums) {
			if(documentoObrigatorioEnum.getId().equals(documentoObrigatorio.getIdeDocumentoObrigatorio())){
				return documentoObrigatorioEnum;
			}
		}
		throw new IllegalArgumentException("Documento Obrigatório não encontrado!");
	}

}
