package br.gov.ba.seia.enumerator;

/**
 * @author antonio.junior
 */
public enum ParametroEnum {

	USUARIO_EXTERNO(1),
	ORGAO_INEMA(2),
	AREA_COINS(3),
	CRONOGRAMA_ITEM_REUNIAO(4),
	CRONOGRAMA_ITEM_CONCLUSAO_INSPECAO(5),
	CRONOGRAMA_ITEM_CONCLUSAO_PARECER(6),
	IDE_PERFIL_COORDENADOR(7),
	IDE_LAC_ERB(8),
	IDE_ESCOLARIDADE(10),
	IDE_LAC_POSTO(11),
	IDE_PERFIL_DIRETOR(12),
	IDE_LAC_TRANSPORTADORA(13),
	IDE_FCE_AGROSSILVOPASTORIL(14),
	IDE_FCE_ASV(15),
	IDE_FCE_INTERVENCAO_BARRAGEM(16),
	DIAS_VENCIMENTO_BOLETO(17),
	VOLUME_FLORESTAL(18),
	IDE_FCE_OUTORGA_CAPTACAO_SUPERFICIAL(19),
	IDE_FCE_ABASTECIMENTO_HUMANO(20),
	IDE_FCE_OUTORGA_CAPTACAO_SUBTERRANEA(21),
	IDE_FCE_OUTORGA_ABASTECIMENTO_INDUSTRIAL(22),
	IDE_FCE_OUTORGA_IRRIGACAO(23),
	IDE_FCE_OUTORGA_PULVERIZACAO(24),
	IDE_FCE_OUTORGA_LANCAMENTO_EFLUENTES(25),
	IDE_FCE_OUTORGA_DESSEDENTACAO_ANIMAL(26),
	IDE_FCE_OUTORGA_PERFURACAO_POCO(27),
	IDE_FCE_INDUSTRIA(28),
	IDE_FCE_OUTORGA_AQUICULTURA(29),
	IDE_FCE_TURISMO(30),
	MAX_PROCESSOS_PAUTA_TECNICA_LIDER(32),
	MAX_PROCESSOS_PAUTA_TECNICA(33),
	MAX_DIAS_EXPIRACAO_SENHA(34),
	MAX_DIAS_INATIVACAO_USUARIO(35),
	HORARIO_ROTINA_INATIVACAO_USUARIO(36),
	HORARIO_ROTINA_NOTIFICACAO_PRAZO(37),
	IDE_ATO_FLUXO_NOUT_ANALISE_TECNICA(38),
	HORARIO_ROTINA_SINAFLOR(39),
	MULTA_ATRASO_CRF(40),
	NUMERO_MAXIMO_EMAIS_POR_CONSULTA(41),
	HORARIO_ROTINA_VERIFICAR_ENVIO_EMAILS(42),
	HORARIO_ROTINA_VERIFICAR_EMAILS_PENDENTES(43),
	HORARIO_ROTINA_ENVIO_COMUNICACAO(44);


	private int ideParametro;

	private ParametroEnum(int pIdeparametro) {
		ideParametro = pIdeparametro;
	}

	public int getIdeParametro() {
		return ideParametro;
	}
}