package br.gov.ba.seia.enumerator;

public enum StatusRequerimentoEnum {
		
		AGUARDANDO_ENQUADRAMENTO(1),
		SENDO_ENQUADRADO(2),
		ENQUADRADO(3),
		EM_VALIDACAO_PREVIA(4),
		VALIDADO(5),
		PAGAMENTO_LIBERADO(6),
		COMPROVANTE_ENVIADO(7),
		FORMADO(8),
		CANCELADO(9),
		PENDENCIA_ENQUADRAMENTO(10),
		PENDENCIA_VALIDACAO(11),
		PENDENCIA_ENVIO_DOCUMENTACAO(12),
		PENDENCIA_VALIDACAO_COMPROVANTE(13),
		REQUERIMENTO_INCOMPLETO(14),
		BOLETO_VALIDADO(15),
		REQUERIMENTO_CONCLUIDO(16),
		RETORNO_STATUS(17),
		BOLETO_EM_PROCESSAMENTO(18),
		DECLARACAO_EMITIDA(19)
	;
	
	private int status;
	
	private StatusRequerimentoEnum(int i) {
		status = i;
	}
	
	public int getStatus() {
		return status;
	}
}