package br.gov.ba.seia.enumerator;

public enum StatusFluxoEnum {
	FORMADO(1),
	CONCLUIDO(2),
	NOTIFICADO(3),
	AGUARDANDO_APROVACAO_NOTIFICACAO(4),
	ENCAMINHADO_PARA_AREA(5),
	ANALISE_TECNICA(6),
	NOTIFICACAO_RESPONDIDA(7),
	NOTIFICACAO_NAO_RESPONDIDA(8),
	NOTIFICACAO_EXPEDIDA(9),
	ARQUIVADO(10),
	ENVIADO_PUBLICACAO(11),
	ENCAMINHADO_PARA_O_GESTOR(12),
	NOTIFICACAO_ALTERADA(13),
	NOTIFICACAO_CANCELADA(14),
	NOTIFICACAO_ENVIADA_PARA_REVISAO(15),
	NOTIFICACAO_CRIADA(16),
	CANCELADO(17),
	REABERTO(18),
	AGUARDANDO_APROVACAO_ANALISE_TECNICA(19),
	ANALISE_TECNICA_APROVADA(20),
	AGUARDANDO_REENQUADRAMENTO_PROCESSO(21),
	PROCESSO_REENQUADRADO(22),
	NAO_REENQUADRADO(23),
	EDITADO_AGUARDANDO_REENQUADRAMENTO(26),
	REENQUADRAMENTO_EM_TRAMITE(27),
	REENQUADRADO_AGUARDANDO_DISTRIBUICAO(28);
	
	
	private int status;
	
	private StatusFluxoEnum(int i) {
		status = i;
	}
	
	public int getStatus() {
		return status;
	}
}