package br.gov.ba.seia.enumerator;

public enum TemaGeoseiaEnum {
	
	LIMITE_PROPRIEDADE(1),
	RESERVA_LEGAL(2),
	APP(3),
	ATIVIDADE_DESENVOLVIDA(4),
	VEGETACAO_NATIVA(5),
	SUPRESSAO_VEGETACAO(6),
	QUEIMADA_CONTROLADA(7),
	PLANO_MANEJO(8),
	EXECUCAO_PLANO_MANEJO(9),
	FLORESTA_PRODUCAO(10),
	SERVIDAO_AMBIENTAL(11),
	LOTE_ASSENTAMENTO(12),
	RPPN(13),
	AREA_RURAL_CONSOLIDADA(14),
	EMPREENDIMENTO(15),
	AREA_LICENCIADA(16),
	AREA_DESMEMBRADA(17),
	AREA_INCORPORADA(18),
	LIMITE_TERRITORIO_PCT(19),
	LIMITE_COMUNIDADE_PCT(20),
	SEDE_COMUNIDADE_PCT(21),
	PRAD_RESERVA_LEGAL(22),
	PRAD_APP(23),
	RESERVA_LEGAL_PCT(98),
	COMUNIDADE_RESERVA_LEGAL_PCT(99);
	
	private Integer id;
	
	TemaGeoseiaEnum(Integer id){
		this.id = id;
	}
	
	public Integer getId() {
		return id;
	}
	
}
