package br.gov.ba.seia.enumerator;

public enum TipoDocumentoImovelRuralEnum {
	
	AUTORIZACAO_DE_OCUPACAO(4),
	ANUENCIA_DA_COORDENACAO_DE_DESENVOLVIMENTO_AGRARIO_CDA_OU_INCRA(5),
	CONCESSAO_REAL_DE_DIREITO_AO_USO(6),
	CONTRATO_DE_ALIENACAO_DE_TERRAS_PUBLICAS(7),
	CONTRATO_DE_CONCESSAO_DE_TERRAS_PUBLICAS(8),
	CONTRATO_DE_TRANSFERENCIA_DE_AFORAMENTO(9),
	LICENCA_DE_OCUPACAO(10),
	TERMO_DE_DOACAO(11),
	TITULO_DE_PROPRIEDADE_SOB_CONDICAO_RESOLUTIVA(12),
	TITULO_DE_DOMINIO(13),
	TITULO_DE_RECONHECIMENTO_DE_DOMINIO(14),
	TITULO_DE_RATIFICACAO(15),
	TITULO_DEFINITIVO_EMITIDO_POR_ORGAOS_OFICIAIS_DE_REGULARIZACAO_FUNDIARIA(16),
	CONTRATO_DE_PROMESSA_DE_COMPRA_E_VENDA(17),
	DECLARACAO_DOS_CONFRONTANTES_COM_ANUENCIA_DO_SINDICATO_DOS_TRABALHADORES_RURAIS(18),
	IMISSAO_DE_POSSE(19),
	CONTRATO_DE_CONCESSAO_DE_DIREITO_REAL_DE_USO(32)
	;

	private Integer id;
	
	private TipoDocumentoImovelRuralEnum(Integer id) {
		this.id=id;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}	
	
}
