
package br.gov.ba.ws.sefaz;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "cls_emissao_documento_arrecadacaoSoap", targetNamespace = "http://www.sefaz.ba.gov.br/warr")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ClsEmissaoDocumentoArrecadacaoSoap {


    /**
     * 
     * @param pxmlRequisicao
     * @return
     *     returns com.thejavageek.client.ObterCamposObrigatoriosResponse.ObterCamposObrigatoriosResult
     */
    @WebMethod(operationName = "obter_campos_obrigatorios", action = "http://www.sefaz.ba.gov.br/warr/obter_campos_obrigatorios")
    @WebResult(name = "obter_campos_obrigatoriosResult", targetNamespace = "http://www.sefaz.ba.gov.br/warr")
    @RequestWrapper(localName = "obter_campos_obrigatorios", targetNamespace = "http://www.sefaz.ba.gov.br/warr", className = "com.thejavageek.client.ObterCamposObrigatorios")
    @ResponseWrapper(localName = "obter_campos_obrigatoriosResponse", targetNamespace = "http://www.sefaz.ba.gov.br/warr", className = "com.thejavageek.client.ObterCamposObrigatoriosResponse")
    public br.gov.ba.ws.sefaz.ObterCamposObrigatoriosResponse.ObterCamposObrigatoriosResult obterCamposObrigatorios(
        @WebParam(name = "Pxml_requisicao", targetNamespace = "http://www.sefaz.ba.gov.br/warr")
        String pxmlRequisicao);

    /**
     * 
     * @param pxmlRequisicao
     * @return
     *     returns com.thejavageek.client.EmitirDocumentoArrecadacaoResponse.EmitirDocumentoArrecadacaoResult
     */
    @WebMethod(operationName = "emitir_documento_arrecadacao", action = "http://www.sefaz.ba.gov.br/warr/emitir_documento_arrecadacao")
    @WebResult(name = "emitir_documento_arrecadacaoResult", targetNamespace = "http://www.sefaz.ba.gov.br/warr")
    @RequestWrapper(localName = "emitir_documento_arrecadacao", targetNamespace = "http://www.sefaz.ba.gov.br/warr", className = "com.thejavageek.client.EmitirDocumentoArrecadacao")
    @ResponseWrapper(localName = "emitir_documento_arrecadacaoResponse", targetNamespace = "http://www.sefaz.ba.gov.br/warr", className = "com.thejavageek.client.EmitirDocumentoArrecadacaoResponse")
    public br.gov.ba.ws.sefaz.EmitirDocumentoArrecadacaoResponse.EmitirDocumentoArrecadacaoResult emitirDocumentoArrecadacao(
        @WebParam(name = "Pxml_requisicao", targetNamespace = "http://www.sefaz.ba.gov.br/warr")
        String pxmlRequisicao);

}
