
package br.gov.ba.ws.sefaz;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "cls_emissao_documento_arrecadacao", targetNamespace = "http://www.sefaz.ba.gov.br/warr", wsdlLocation = "file:/home/lesantos/Downloads/CERH/webservice_DAE/warrEmissaoDocumentoArrecadacao.asmx.wsdl")
public class ClsEmissaoDocumentoArrecadacao
    extends Service
{

    private final static URL CLSEMISSAODOCUMENTOARRECADACAO_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.gov.ba.ws.sefaz.ClsEmissaoDocumentoArrecadacao.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.gov.ba.ws.sefaz.ClsEmissaoDocumentoArrecadacao.class.getResource(".");
            url = new URL(baseUrl, "file:/home/lesantos/Downloads/CERH/webservice_DAE/warrEmissaoDocumentoArrecadacao.asmx.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/home/lesantos/Downloads/CERH/webservice_DAE/warrEmissaoDocumentoArrecadacao.asmx.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CLSEMISSAODOCUMENTOARRECADACAO_WSDL_LOCATION = url;
    }

    public ClsEmissaoDocumentoArrecadacao(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClsEmissaoDocumentoArrecadacao() {
        super(CLSEMISSAODOCUMENTOARRECADACAO_WSDL_LOCATION, new QName("http://www.sefaz.ba.gov.br/warr", "cls_emissao_documento_arrecadacao"));
    }

    /**
     * 
     * @return
     *     returns ClsEmissaoDocumentoArrecadacaoSoap
     */
    @WebEndpoint(name = "cls_emissao_documento_arrecadacaoSoap")
    public ClsEmissaoDocumentoArrecadacaoSoap getClsEmissaoDocumentoArrecadacaoSoap() {
        return super.getPort(new QName("http://www.sefaz.ba.gov.br/warr", "cls_emissao_documento_arrecadacaoSoap"), ClsEmissaoDocumentoArrecadacaoSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClsEmissaoDocumentoArrecadacaoSoap
     */
    @WebEndpoint(name = "cls_emissao_documento_arrecadacaoSoap")
    public ClsEmissaoDocumentoArrecadacaoSoap getClsEmissaoDocumentoArrecadacaoSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.sefaz.ba.gov.br/warr", "cls_emissao_documento_arrecadacaoSoap"), ClsEmissaoDocumentoArrecadacaoSoap.class, features);
    }

}
